# Generated by Django 4.1.7 on 2025-04-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
