# Generated by Django 4.1.7 on 2025-04-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0002_remove_user_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
